 # Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


def p2():
    sum = 2
    f1 = 1
    f2 = 2
    while True:
        f = fibonacci(f1, f2)
        if f > 4000000:
            break
        if f % 2 == 0:
            sum += f
        f1 = f2
        f2 = f
    return sum


def fibonacci(a, b):
    return a + b


print p2()

